### PR TITLE
Raidz instead of mirror for 3+ drives

### PR DESCRIPTION
**Pull request by Zapunidi**
Previously in the script all multiple drives created a mirror. For systems will multiple 3+ drives the intended purpose is a compromise between space and redundancy.
I changed the behaviour from always mirror to mirror bpool on all drives and raidz for rpool if there are 3 or more drives.
There are drawbacks that people with 4-5+ drives may want either raidz, raidz2 or raidz3. It would be nice to allow user to select the redundancy level, but that was beyond my bash skills.
I chose to mirror bpool on all drives thus wasting boot partition space because of two reasons. First, boot is a priority and wasting a little space knowing that either drive will allow boot worth it. Second, I made tests with raidz on bpool: removing the drives one by one, checking boot, restoring drive, resilvering and so on. For reasons unknown I ended with a system that can boot from 2/3 drives, but not from 3/3. On all drives I just got grub very basic console. On the mirrored bpool I succesfully finished that test.

### CODE REVIEW

**Comment by saveriomiroddi** [comment]
Hello! Thanks for the contribution! I will review it over the next solar week. In the meanwhile, it needs to be rebased - I did very radical changes in the last days, due to the Ubuntu 20.04 support, so PRs written in the meanwhile have been outdated :grimacing: 

By the way, if you like shell scripting/Bash, a fun way to improve the skills is https://exercism.io :slightly_smiling_face:

**Comment by saveriomiroddi** [comment]
So! The PR looks ok to me. This game me an idea for a smooth, more flexibile, implementation in the future.

Once it's rebased, it can go in.

I can rebase it for you, then merge it in - it will require me to close this PR, but your commit will be included in your GitHub contributions counter :slightly_smiling_face:.

**Comment by Zapunidi** [comment]
> I can rebase it for you, then merge it in - it will require me to close this PR, but your commit will be included in your GitHub contributions counter slightly_smiling_face.

Sorry for late reply. I have not much free time for community works. I will do rebase myself in a couple of days or you can do it yourself, as you suggested.
I didn't know there is a contribution counter :) I just see your implementation of ZFS on root installation so much more suitable than one built-in Ubuntu 20.04, so I couldn't walk by.

**Comment by saveriomiroddi** [comment]
> Sorry for late reply. I have not much free time for community works. I will do rebase myself in a couple of days or you can do it yourself, as you suggested.
> I didn't know there is a contribution counter :) I just see your implementation of ZFS on root installation so much more suitable than one built-in Ubuntu 20.04, so I couldn't walk by.

Hello! Don't worry. Whoever does it first :smile: 

Commits in PRs that get mainlined count in the "contributions in the last year" diagram. Contributors generally care about that diagram, so I help them as I can :slightly_smiling_face:.

**Comment by saveriomiroddi** [comment]
I've cherry-picked the commit in #111. It will go out on the next stable release (I may perform some modifications; it gave me an interesting idea!).

Thanks for the contribution!

**Pull request closed without merging**
