### PR TITLE
Changes to ZFS repo source, added support for ElementaryOS

### PR DESCRIPTION
**Pull request by VltraHeaven**
Since Jonathan F's ZFS PPA is no longer publicly available I replaced this PPA with the Ubuntu Universe repo and added support for Elementary OS. Tests were completed using in a VM on the  VMware Workstation 15.5 hypervisor.

### CODE REVIEW

**Comment by saveriomiroddi** [comment]
Hello!

Thanks for the PR. I'll review over this week, and give feedback. I've self-requested the review :smile:

**Comment by saveriomiroddi** [comment]
@VltraHeaven I've cherry picked (and modified as necessary) one of your commits into a [separate PR](https://github.com/saveriomiroddi/zfs-installer/pull/32).

I can't merge the rest of this PR though, for a few reasons:

1. There are multiple commits for a single logical unit of work (= ElementaryOS support), which are essentially corrections of the first - they should be squashed, as they don't add value in the context of a new PR
2. The first commit also includes two separate units of work: the presumed correction of the ZFS jonathon repository problem, and the support for ElementaryOS. While this is, generally speaking, a design problem, in this context is a practical problem. The repository correction doesn't work, so it prevents following up with the PR (review, changes, merge). If they had been split into two PRs, I could follow up.
3. The branch needs to be rebased.

I'll think about how to best proceed, while still including your work. At a minimum, the repository correction should be removed, and the PR should be rebased.

Sorry for this, but as it is, this PR creates a problem. I'm still trying to mainline as much as possible of your work, though :smile:

**Comment by saveriomiroddi** [comment]
I'm closing this PR because in addition to the problems above, I've also found another issue, and at this point, trying hard to modify the PR commits doesn't make sense.

Specifically, [adding the `universe` repository](https://github.com/VltraHeaven/zfs-installer/commit/99c66d976af325c0c74b207fe0abeeddbacbf08f#diff-761944bb90b658235bf6861db38b75e7R426):

```sh
add-apt-repository --yes universe
```

is not required. On a freshly booted ElementaryOS machine, the `universe` repository is already included:

```sh
# add-apt-repository universe
'universe' distribution component is already enabled for all sources.
```

**Comment by saveriomiroddi** [comment]
@VltraHeaven I've just merged into stable the new ElementaryOS support - the PR merged is #34.

**Comment by VltraHeaven** [comment]
@saveriomiroddi  Thank you for the comments breaking down ways that I can make my commits more detailed, structured and concise. I'll continue to come back to these suggestions in the future to make sure my contributions bring benefit to open source projects and less disarray. Thank you for your diligence and have a great day!

**Pull request closed without merging**
